### ISSUE TITLE
RotationAction

### ISSUE THREAD

**Issue by a-gurin** [Schaka/wRobotFightclassFrameworkEnhanced#1]
Hi,
How to use items or Lua Script in RotationAction? For example use HealthStone at Me.HealthPercent <= 50
Thanks

**Comment by Schaka** [comment]
Example of Lua:

`new RotationStep(new RotationLua("CastSpellByName('Shoot')", 5), 0.5f, (s, t) => Me.HealthPercent <= 30 && Me.ManaPercentage > 15 && RotationCombatUtil.IsAutoRepeating("Shoot"), RotationCombatUtil.BotTarget, true),`

Example of Raw C#:
`new RotationStep(new RotationRawAction(() => ItemsManager.UseItem(HealthstoneDictionary[Healthstone]), 5), 4.03f, (s, t) => Me.HealthPercent < 40 && ItemsHelper.GetItemCount(HealthstoneDictionary[Healthstone]) > 0 && ItemsHelper.GetItemCooldown(HealthstoneDictionary[Healthstone]) == 0, RotationCombatUtil.FindMe),`
